nodeselector: {}

images:
  app:
    image: ghcr.io/ldest/sre-course/api
    pullPolicy: IfNotPresent
    tag: "7c04bc9"

deployments:
  app:
    name: app
    replicas: 1
    labels:
      app: app
    port: 80
    resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 128Mi
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz/ready
        port: 80
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 10
    livenessProbe:  
      failureThreshold: 3
      httpGet:
        path: /healthz/live
        port: 80
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 10        

variables:
  app:
    DOTNET_ENVIRONMENT: Development

secret:
  app:
    server: "91.185.85.240"
    port: "5000"
    database: sre
    user_id: mydb-user
    password: "xxx"

ingress:
  app: sre-app.rndhelp.ru      

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}

podSecurityContext: {}