---
apiVersion: v1
kind: ConfigMap
data:
  {{- range $key, $value := .Values.variables.app }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  ConnectionStrings__PgConnection: "server={{ .Values.secret.app.server }}; port={{ .Values.secret.app.port }}; database={{ .Values.secret.app.database }}; user id={{ .Values.secret.app.user_id }}; password={{ .Values.secret.app.password }};"
metadata:
  name: app

