apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployments.app.name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 4m
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
    kubernetes.io/ingress.class: nginx
  labels:
    app: {{ .Values.deployments.app.name }}
spec:
  rules:
  - host: {{ .Values.ingress.app }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.deployments.app.name }}
              port:
                number: {{ .Values.deployments.app.port }}