---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.deployments.app.name }}
  labels:
    {{- with .Values.deployments.app.labels }}
      {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- with .Values.deployments.app.labels }}
        {{- toYaml . | nindent 6}}
      {{- end }}