{
 "title": "4 Golden Signal",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic  Ingrerss Nginx ",
   "type": "timeseries",
   "description": "Траффик на вх. ingrees по хосту \n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/nginxvdvsdv/nginx-ingress-controller?orgId=1&refresh=5s",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{host=\"sre-app.rndhelp.ru\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "sre-app.rndhelp.ru"
    }
   ]
  },
  {
   "title": "Active sessions postgresql ",
   "type": "timeseries",
   "description": "Кол-во соединений в postgrsql \n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/000000039/postgresql-database?orgId=1&refresh=10s\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/000000039/postgresql-database?orgId=1&refresh=10s",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}} , {{instance}}"
    },
    { "expr": "pg_settings_max_connections{}", "legendFormat": "max_connections" }
   ]
  },
  {
   "title": "Исходящий трафика из кубернетес контейнера ",
   "type": "timeseries",
   "description": "передача трафика из кубера  ns sre-cource-student-53",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"sre-cource-student-53\"}[2m]) or\r\nlabel_replace(irate(container_network_transmit_bytes_total{namespace=\"sre-cource-student-53\"}[2m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")",
     "legendFormat": "{{interface}} : [{{pod}}]"
    }
   ]
  },
  {
   "title": "Входящий  траффик в кубернетес  контейнер ",
   "type": "timeseries",
   "description": "ns sre-cource-student-53",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"sre-cource-student-53\"}[2m]) or label_replace(irate(container_network_receive_bytes_total{namespace=\"sre-cource-student-53\"}[2m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")",
     "legendFormat": "{{interface}} : [{{pod}}]"
    }
   ]
  },
  { "title": "Lattency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Lattency  ingress  nginx ",
   "type": "timeseries",
   "description": "Время ответа сервиса отвечающая за  хост sre-app.rndhelp.ru  ,метрики с ingress-nginx \n",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,(rate(nginx_ingress_controller_response_duration_seconds_bucket{host=\"sre-app.rndhelp.ru\", status!~\"[4-5].*\"}[5m])))",
     "legendFormat": "{{ instance }} {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration BlackBox",
   "type": "graph",
   "description": "Возвращает время завершения проверки в секундах c внешней проверки black-box\n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/NEzutrbMkdvsdvsdvsdvsd/blackbox-exporter-http-prober?orgId=1&refresh=1m&var-job=blackbox_sre&var-instance=All\n\n",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"http://sre-app.rndhelp.ru/cities\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Longest Transaction Postgresql",
   "type": "graph",
   "description": "Время транзакции в postgresql \n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/5474745/postgresql-overview-postgres_exporter?orgId=1&refresh=5m",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{} > 0",
     "legendFormat": "{{instance}} {{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Disk средние время обр. к дискам ",
   "type": "timeseries",
   "description": "Среднее время обработки запросов, отправленных на устройство. Сюда входит время, проведенное запросами в очереди, и время, затраченное на их обслуживание.\n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/rYdddlPWksdvsdvsd/node-exporter-full?orgId=1",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{}[$__rate_interval]) / irate(node_disk_reads_completed_total{}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} - Read wait time avg"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{}[$__rate_interval]) / irate(node_disk_writes_completed_total{}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} - Write wait time avg"
    }
   ]
  },
  { "title": "Насыщение", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info\n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/rYdddlPWksdvsdvsd/node-exporter-full?orgId=1",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Busy System  {{ instance }} "
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[$__rate_interval])))",
     "legendFormat": "Busy User {{ instance }} "
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage\n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/rYdddlPWksdvsdvsd/node-exporter-full?orgId=1",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - (node_memory_Cached_bytes{} + node_memory_Buffers_bytes{} + node_memory_SReclaimable_bytes{})",
     "legendFormat": "RAM Used {{instance}}"
    },
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "RAM Total {{ instance }}" }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Процент запылённости места на диске \n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/rYdddlPWksdvsdvsd/node-exporter-full?orgId=1",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "Обращение к диску I/O  \n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/rYdddlPWksdvsdvsd/node-exporter-full?orgId=1",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "description": "Кол-во соединений в postgrsql \n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/000000039/postgresql-database?orgId=1&refresh=10s",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}} , {{instance}}"
    },
    { "expr": "pg_settings_max_connections{}", "legendFormat": "max_connections" }
   ]
  },
  {
   "title": "Read IOPS kubernetes приложение ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{namespace=\"sre-cource-student-53\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS kubernetes приложение ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{namespace=\"sre-cource-student-53\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Error (4xx|5xx responses)",
   "type": "timeseries",
   "description": "Процент не удачных запросов \n\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/nginxvdvsdv/nginx-ingress-controller?orgId=1&refresh=5s",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=\"sre-app.rndhelp.ru\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{host=\"sre-app.rndhelp.ru\"}[2m])) by (ingress)",
     "legendFormat": "sre-app.rndhelp.ru"
    }
   ]
  },
  {
   "title": "Error code http",
   "type": "graph",
   "description": "Частота появление ошибок 4xx и 5xx\nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/nginxvdvsdv/nginx-ingress-controller?orgId=1&refresh=5s",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=\"sre-app.rndhelp.ru\",status=~\"5.*\"}[5m])) / sum(rate(nginx_ingress_controller_requests{host=\"sre-app.rndhelp.ru\"}[5m]))",
     "legendFormat": "error 50x"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=\"sre-app.rndhelp.ru\",status=~\"4.*\"}[5m])) / sum(rate(nginx_ingress_controller_requests{host=\"sre-app.rndhelp.ru\"}[5m]))",
     "legendFormat": "error 40x"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "description": "Конфликты транзакции или подвшие изменения в postgresql   \nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/5474745/postgresql-overview-postgres_exporter?orgId=1&refresh=5m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_conflicts{}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "rate(pg_stat_database_deadlocks{}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "description": "Ошибки на стороне сетев трафика на VM \nhttp://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/rYdddlPWksdvsdvsd/node-exporter-full?orgId=1",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{}[$__rate_interval])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  }
 ]
}