---
# defaults file for roles/prometheus

prometheus_dir_configuration: "/etc/prometheus"
prometheus_retention_time: "5d"
prometheus_scrape_interval: "30s"
prometheus_node_exporter: true
prometheus_node_exporter_group: "all"
etcd: 
  - 192.168.10.5
  - 192.168.10.6
  - 192.168.10.7
prometheus_env: "production"
prometheus_var_config:
  global:
    scrape_interval: "{{ prometheus_scrape_interval }}"
    evaluation_interval: 5s
    external_labels:
      env: '{{ prometheus_env }}'
  scrape_configs:
    - job_name: prometheus
      basic_auth:
        username: admin
        password: "crhsnysq"
      scrape_interval: 2m
      static_configs:
        - targets: ['{{ inventory_hostname }}:9090']

