groups:
  - name: latency
    rules:
    - alert: BlackboxSlowProbe
      expr: avg_over_time(probe_duration_seconds[1m]) > 4
      for: 30s
      labels:
        severity: warning
        sre: GoldSignal
      annotations:
        summary: Blackbox slow probe (instance {{ $labels.instance }})
        value: "{{ $value }}"
        description: "Blackbox probe took more than 4s to complete\n  VALUE = {{ $value }}\n {{ $labels.instance }}\n instance: {{ $labels.instance }}"
        Dashboard: "http://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/NEzutrbMkdvsdvsdvsdvsd/blackbox-exporter-http-prober?orgId=1&refresh=1m&viewPanel=4"
    - alert: Detected_long_requests_ingress_nginx 
      expr: histogram_quantile(0.9, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{host="sre-app.rndhelp.ru", status!~"[4-5].*"}[5m])) by (le, host)) > 4
      for: 1m
      labels:
        severity: warning
        sre: GoldSignal
      annotations:
        summary: "{{ $labels.host }} \n VALUE = {{ $value }} is long requests more {{ $value }} sec."
        description: "{{ $labels.host }}  \n VALUE = {{ $value }} is long requests more {{ $value }} sec.on {{ $labels.host }}"
        value: "{{ $value }}"
        dashboard: "http://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/7GKkdrGIz/4-golden-signal?orgId=1&viewPanel=10"   
    - alert: Longest_Transaction_Postgresql
      expr: pg_stat_activity_max_tx_duration{} > 3
      for: 1m
      labels:
        severity: warning
        sre: GoldSignal
      annotations:
        summary: "Longest_Transaction_Postgresql {{ $labels.instance }}"
        description: "{{ $labels.instance }}  \n VALUE = {{ $value }} is long requests more {{ $value }} sec.on {{ $labels.host }}"
        value: "{{ $value }}"
        dashboard: "http://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/7GKkdrGIz/4-golden-signal?orgId=1&viewPanel=52"      
    - alert: UnusualDiskReadLatency
      expr:  rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 100
      for: 2m
      labels:
        severity: warning
        sre: GoldSignal   
      annotations:
        summary: "Unusual disk write latency {{ $labels.instance }}"
        description: "{{ $labels.instance }}  \n VALUE = {{ $value }}"
        value: "{{ $value }}"  
        dashboard: "http://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/7GKkdrGIz/4-golden-signal?orgId=1&editPanel=54" 
    - alert: UnusualDiskWriteLatency
      annotations:
        description: |-
          Disk latency is growing (write operations > 100ms)
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Unusual disk write latency (instance {{ $labels.instance }})
        value: "{{ $value }}" 
        dashboard: "http://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/7GKkdrGIz/4-golden-signal?orgId=1&editPanel=54" 
      expr: rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 100
      for: 2m
      labels:
        project: pochtabank
        sre: GoldSignal   
    - alert: BlackboxProbeSlowHttp
      expr: avg_over_time(probe_http_duration_seconds[1m]) > 3
      for: 1m
      labels:
        severity: warning
        value: "{{ $value }}" 
        sre: GoldSignal 
      annotations:
        summary: Blackbox slow probe (instance {{ $labels.instance }})
        description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"   
        dashboard: "http://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/NEzutrbMkdvsdvsdvsdvsd/blackbox-exporter-http-prober?orgId=1&refresh=1m"
    - alert: HostUnusualDiskIo
      expr: (rate(node_disk_io_time_seconds_total[1m]) > 0.5) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
      for: 5m
      labels:
        severity: warning
        sre: GoldSignal
      annotations:
        summary: Host unusual disk IO (instance {{ $labels.instance }})
        description: "Time spent in IO is too high on {{ $labels.instance }}. Check storage for issues.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"   
        dashboard: "http://5eca9364-3899-4021-b861-fd4f64e48c6d.mts-gslb.ru/d/7GKkdrGIz/4-golden-signal?orgId=1&viewPanel=54"    